### ISSUE TITLE
Private Paths

### ISSUE THREAD

**Issue by njuweicheng** [PCART-tools/PCBench#1]
Thanks for your valuable work. 

I have noticed that there are many private paths in PCBench that affect the execution, e.g. looking up "/home/zhang" in the repository. Can you provide the corresponding file and change it to a relative path? Or any other feasible solution. 

I look forward to your reply, thank you!

**Comment by guanpingxiao** [comment]
Thanks for your comment. Will fix it in the next few days.

Guanping

**Comment by guanpingxiao** [comment]
@njuweicheng 

Hi, we have uploaded the corresponding files for execution and changed their paths to relative ones. Thanks.

Guanping

**Comment by njuweicheng** [comment]
Thanks for the quick response!

**Comment by njuweicheng** [comment]
Hi, I am interested in this work but still struggling with execution issues. 

Note: I execute the code snippet by "cd \<dir> \&\& <conda_env> \<filename>".

- Relative paths: please kindly test the execution of all testcases in the current version and address the failures. For example, I encountered `FileNotFoundError: [Errno 2] No such file or directory: ‘fasttext’: ‘fasttext’` in `Benchmark/gensim/gensim.models.wrappers.fasttext.FastText.train@2.2.0-2.3.0/gensim.models.wrappers.fasttext.FastText.train#50YY/trainYY.py`, which can be solved by changing the path to `'. /fasttext'` in the code.

- Conda envs: in fact it is not always possible to restore to a conda environment from a .yml file. For example, I fail to create `gensim2.2.0` and `gensim3.0.0` by using `Benchmark/gensim/gensim.models.wrappers.fasttext.FastText.train@2.2.0-2.3.0/gensim2.2.0.yml` and `Benchmark/gensim/gensim.models.ldamodel.LdaModel.diff@2.3.0-3.0.0/gensim3.0.0.yml`, respectively. They encountered a strange error when installing `gensim`: `distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('numpy>=1.11.3')`. In addition, environments installed from .yml files may change over time, such as the deletion of a certain version, which would threaten the stability of this benchmark. I strongly recommend the authors to provide offline execution environments, such as conda pack or anything available.

Thank you!

**Comment by guanpingxiao** [comment]
- Relative paths: which OS did you use to execute the code snippet? I tested the case in Ubuntu 18.04 without any problems. For example, `cd gensim.models.wrappers.fasttext.FastText.train#50YY` & `python trainYY.py`.

**Comment by njuweicheng** [comment]
I executed them in Ubuntu 20.04.1 LTS.

Before:
![1724137961984](https://github.com/user-attachments/assets/f45fe21c-80c0-4fde-9383-fae4aa4474fa)

After:
![1724138107778](https://github.com/user-attachments/assets/5e92c81c-dbbe-47d5-a0e7-5afbada08ac7)

I'm not sure if this is related to OS, but it looks that prefixing relative paths with `'. /'`  would be more robust.

**Comment by guanpingxiao** [comment]
![image](https://github.com/user-attachments/assets/f92b8d8e-dd3a-4f89-932b-59bbe07d282b)

It seems like an OS-related issue...

**Comment by guanpingxiao** [comment]
![60e8e1767539402af1d86c7ee1cb827](https://github.com/user-attachments/assets/2237bd71-3f6f-47d0-977b-dad9f7b12d53)
Confirmed. It is an OS-related issue. We will add `./` in the paths. Thank you.

**Comment by guanpingxiao** [comment]
- Conda envs: Thanks for your suggestion. We will upload the envs by conda pack.

**Comment by guanpingxiao** [comment]
@njuweicheng 

Hi, we have fixed the OS-related issue by adding `./` to the local files' paths. Besides, we have uploaded the conda virtual environments produced by conda-pack. Please refer to the updated `README.md` for details. 

Feel free to ask any questions. Thank you.
